# QUESTION - 1
# WAP to print twinkle twinkle little star poem using python print function.

print("Twinkle, twinkle, little star,")
print("    How I wonder what you are!") 
print("        Up above the world so high,")
print("        Like a diamond in the sky.")
print("When the blazing sun is gone,")
print("When he nothing shines upon,")
print("Then you show your little light,")
print("Twinkle, twinkle, all the night.")
print("Then the trav'ller in the dark,")
print("Thanks you for your tiny spark,")
print("He could not see which way to go,")
print("If you did not twinkle so.")
print("In the dark blue sky you keep,")
print("And often thro' my curtains peep,")
print("For you never shut your eye,")
print("Till the sun is in the sky.")
print(" 'Tis your bright and tiny spark,")
print("    Lights the traveler in the dark,")
print("    Tho' I know not what you are,")
print("Twinkle, twinkle, little star.")
print()
print()
#                                        OR


print(''' Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

When the blazing sun is gone,
When he nothing shines upon,
Then you show your little light,
Twinkle, twinkle, all the night.

Then the trav'ller in the dark,
Thanks you for your tiny spark,
He could not see which way to go,
If you did not twinkle so.

In the dark blue sky you keep,
And often thro' my curtains peep,
For you never shut your eye,
Till the sun is in the sky.

'Tis your bright and tiny spark,
Lights the trav'ller in the dark:
Tho' I know not what you are,
Twinkle, twinkle, little star.''')
# -----------------------------------------------------------------------------------------------------------------------------------

